# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class PScan < Formula
  desc "Fast TCP Port Scanner."
  homepage "https://github.com/zhuima/pScan"
  version "1.1.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/zhuima/pScan/releases/download/v1.1.0/pScan_1.1.0_Darwin_arm64.tar.gz"
      sha256 "f28048285d55490c121bfc3706149ba85acc65f18720f34456ba8190c22e4216"

      def install
        bin.install "pScan"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/zhuima/pScan/releases/download/v1.1.0/pScan_1.1.0_Darwin_x86_64.tar.gz"
      sha256 "15458e76bf5e4a44e1b39524c3a8704c17cccdcbf8d47cfe4f64987200e5a667"

      def install
        bin.install "pScan"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/zhuima/pScan/releases/download/v1.1.0/pScan_1.1.0_Linux_x86_64.tar.gz"
      sha256 "e93d1db8968577e5407aa9d6360e245472a6d3f921f0b29cfbcbff840cc847a0"

      def install
        bin.install "pScan"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/zhuima/pScan/releases/download/v1.1.0/pScan_1.1.0_Linux_arm64.tar.gz"
      sha256 "6b1701e59359a4d36b1da3435e15e869368f1c5c748cbd1a94063fbaaa233d34"

      def install
        bin.install "pScan"
      end
    end
  end
end
