# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class PScan < Formula
  desc "Fast TCP Port Scanner."
  homepage "https://github.com/zhuima/pScan"
  version "1.0.7"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/zhuima/pScan/releases/download/v1.0.7/pScan_1.0.7_Darwin_arm64.tar.gz"
      sha256 "722689e8700e2ba428ff9080d2610dcac476a26706579fdc291ceb28bdf5b00d"

      def install
        bin.install "pScan"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/zhuima/pScan/releases/download/v1.0.7/pScan_1.0.7_Darwin_x86_64.tar.gz"
      sha256 "09e5d4351daff17962ffe0fe7aaddf86ca58a7972c86ecacfe487a8b68d57e62"

      def install
        bin.install "pScan"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/zhuima/pScan/releases/download/v1.0.7/pScan_1.0.7_Linux_arm64.tar.gz"
      sha256 "d0f1372dd76a36cbbf96c420989e8e6d154276026a68943e52c7586d5f9e30b0"

      def install
        bin.install "pScan"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/zhuima/pScan/releases/download/v1.0.7/pScan_1.0.7_Linux_x86_64.tar.gz"
      sha256 "aad69c1a5b6d5b70614e155bad4c9dae2392a09026c7ca01f914599fceb27f94"

      def install
        bin.install "pScan"
      end
    end
  end
end
