# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pscan < Formula
  desc "Fast TCP Port Scanner."
  homepage "https://github.com/zhuima/pScan"
  version "1.1.21"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/zhuima/pScan/releases/download/v1.1.21/pscan_1.1.21_Darwin_x86_64.tar.gz"
      sha256 "249f648c55ac3b4f2602991dce352fa9a5e2f64f5d2228b6bd57c801ba3e5e5a"

      def install
        bin.install "pscan"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/zhuima/pScan/releases/download/v1.1.21/pscan_1.1.21_Darwin_arm64.tar.gz"
      sha256 "509dd7f0cdb610d6bd34868330727d3a662dd7e23492c8eba5dc9aff49977e2e"

      def install
        bin.install "pscan"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/zhuima/pScan/releases/download/v1.1.21/pscan_1.1.21_Linux_x86_64.tar.gz"
      sha256 "c94ab498a03c962020be433c59fc2e58ee2c70a52e0dba300a8176547d250fdf"

      def install
        bin.install "pscan"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/zhuima/pScan/releases/download/v1.1.21/pscan_1.1.21_Linux_arm64.tar.gz"
      sha256 "0528dddf30d01e4c8592883048f83d27aed2fe8e17aaaffd755b7e78ba214b30"

      def install
        bin.install "pscan"
      end
    end
  end
end
