# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pscan < Formula
  desc "Fast TCP Port Scanner."
  homepage "https://github.com/zhuima/pScan"
  version "1.1.6"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/zhuima/pScan/releases/download/v1.1.6/pscan_1.1.6_Darwin_arm64.tar.gz"
      sha256 "008c2dc7d792d3824a77f9636b72a91da82f3ac58c1b21b3e6767a4c04988ab7"

      def install
        bin.install "pscan"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/zhuima/pScan/releases/download/v1.1.6/pscan_1.1.6_Darwin_x86_64.tar.gz"
      sha256 "d616b5ffcddc08c3601424f02f274c5e1e2f3c400d7222d513382986083de1af"

      def install
        bin.install "pscan"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/zhuima/pScan/releases/download/v1.1.6/pscan_1.1.6_Linux_x86_64.tar.gz"
      sha256 "c9f9c733f3c0a6f76816f463c3181ee54df110cff09465e535be718c1fbe4d93"

      def install
        bin.install "pscan"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/zhuima/pScan/releases/download/v1.1.6/pscan_1.1.6_Linux_arm64.tar.gz"
      sha256 "e29feac502ebf60a2913e37fe1a25500d06be9e5bf8ad54b1ee9e43993e39f59"

      def install
        bin.install "pscan"
      end
    end
  end
end
